extends Node

# ======================
# = List of Port Names =
# ======================
var port_names = [
	"Coral Cove",
	"Northrop's Reach",
	"Leviathan's Rest",
	"Kraken's Hold",
	"Starfish Point",
	"Siren's Call Seaport",
	"Coral Reef Port",
	"Seaweed Cove Harbor",
	"Squid's Rest Dock",
	"Narwhal's Reach Harbor",
	"Whale's Way Port",
	"Marlin's Marina",
	"Seagull's Rest Harbor",
	"Dolphin's Harbor Dock",
	"Blue Marlin Marina",
	"Seashell Shore Seaport",
	"Coral Coast Port",
	"Hammerhead Bay Port",
	"Sea Turtle's Rest Terminal",
	"Dolphin's Cove Dock",
	"Swordfish Harbor",
	"Seaweed Harbor",
	"Lobster's Bay Landing",
	"Squid's Harbor",
	"Seashell Bay Port",
	"Crab Cove Dock",
	"Narwhal's Port",
	"Whale's Rest Harbor",
	"Nautilus's Cove",
	"Coral Harbor",
	"Sea Urchin's Landing",
	"Anemone's Cove",
	"Marlin's Cove",
	"Seagull's Bay Harbor",
	"Dolphin's Bay Dock",
	"Seashell Cove Port",
	"Coral Bay",
	"Hammerhead Port",
	"Octopus's Harbor",
	"Dolphin's Port",
	"Swordfish Bay Port",
	"Coral Port",
	"Seaweed Port",
	"Lobster's Cove",
	"Squid's Port",
	"Seashell Port",
	"Narwhal's Harbor",
	"Whale's Cove",
	"Nautilus's Harbor",
	"Sea Urchin's Port",
	"Anemone's Harbor",
	"Marlin's Port",
	"Seagull's Port",
	"Seashell Harbor",
	"Octopus's Port",
	"Sea Turtle's Port",
	"Swordfish Port",
	"Lobster's Port",
	"Whale's Port"
]

# ======================
# = List of Port Names =
# ======================
var ship_names = [
	"Sea Serpent",
	"Golden Marlin",
	"Crimson Tide",
	"Silver Phoenix",
	"Emerald Horizon",
	"Neptune's Jewel",
	"Black Pearl",
	"Sapphire Skies",
	"Ivory Voyager",
	"Oceanic Fortune",
	"Azure Galleon",
	"Ruby Rose",
	"Diamond Voyager",
	"Stormy Petrel",
	"Crimson Corsair",
	"Emerald Empress",
	"Silver Swan",
	"Golden Horizon",
	"Neptune's Pride",
	"Sapphire Siren",
	"Black Marlin",
	"Ivory Star",
	"Oceanic Dream",
	"Ruby Raider",
	"Diamond Dragon",
	"Stormy Seahawk",
	"Crimson Cruiser",
	"Emerald Enchantress",
	"Silver Sovereign",
	"Golden Griffin",
	"Neptune's Legacy",
	"Sapphire Storm",
	"Black Sparrow",
	"Ivory Pearl",
	"Oceanic Voyager",
	"Ruby Raven",
	"Diamond Dolphin",
	"Stormy Voyager",
	"Crimson Clipper",
	"Emerald Explorer",
	"Silver Shark",
	"Golden Gale",
	"Neptune's Fury",
	"Sapphire Serenade",
	"Black Phoenix",
	"Ivory Fortune",
	"Oceanic Queen",
	"Ruby Regent",
	"Diamond Dancer",
	"Stormy Sloop",
	"Crimson Crusader",
	"Emerald Eagle",
	"Silver Seahorse",
	"Golden Gull",
	"Neptune's Bounty",
	"Sapphire Swan",
	"Black Dolphin",
	"Ivory Isle",
	"Oceanic Nomad",
	"Ruby Riptide"
]
